name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Trigger on version tags (v1.0.0, etc.)
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          target: ${{ matrix.target }}
          override: true
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Check formatting
        if: matrix.rust == 'stable'
        run: cargo fmt -- --check
      
      - name: Run clippy
        if: matrix.rust == 'stable'
        run: |
          cargo clippy -- -D warnings
          cargo clippy --tests -- -D warnings
      
      - name: Run tests
        run: |
          cargo test --verbose --lib --tests --no-fail-fast
          cargo test --verbose --test proptests --no-fail-fast
          cargo test --verbose --test integration --no-fail-fast
        env:
          RUST_BACKTRACE: full
          
      - name: Check examples (without running them)
        if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
        run: |
          # Just check compilation of examples without running them
          cargo check --examples
          
      - name: Check benches (without running them)
        if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
        run: |
          # Just check compilation of benches without running them
          cargo check --benches

  publish:
    name: Publish to crates.io
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo login $CARGO_REGISTRY_TOKEN
          cargo publish --no-verify
